### ISSUE TITLE
Proper way to cite?

### ISSUE THREAD

**Issue by Parskatt** [TruongKhang/TopicFM#1]
Could you provide a bibfile for referencing your paper?

**Comment by TruongKhang** [comment]
Hi @Parskatt,

You can cite directly BibTeX generated on google scholar as follows

    @article{giang2022topicfm,
        title={TopicFM: Robust and Interpretable Topic-assisted Feature Matching},
        author={Giang, Khang Truong and Song, Soohwan and Jo, Sungho},
        journal={arXiv preprint arXiv:2207.00328},
        year={2022}
    }

**Comment by Parskatt** [comment]
Thanks :)
