### ISSUE TITLE
Runtime

### ISSUE THREAD

**Issue by TuanTNG** [TruongKhang/TopicFM#11]
Hi, 
Thank you for your excellent work.

I have a question about the inference time compared to LofTR.
Because I do not have a computer with GPU here, I cannot run the section "Runtime comparison" as suggested in the readme.
Thus, can you please show me the inference time of TopicFM and LofTR?

I am looking forward to hearing from you soon.

**Comment by TruongKhang** [comment]
Hi @TuanTNG , I provided a runtime report in the supplementary section [here](https://arxiv.org/pdf/2207.00328.pdf) (page 12)

**Comment by TuanTNG** [comment]
Hi @TruongKhang,

Excellent.
Thank you so much.
