### ISSUE TITLE
this is a question

### ISSUE THREAD

**Issue by LooperzZ** [TruongKhang/TopicFM#15]
Hello author, which version of the code corresponds to TopicFM+? Which version of the code corresponds to TopicFM_fast? I use the code corresponding to TopicFM to run the above two weight files and will report an error, which can only correspond to model_best this weight file.

**Comment by TruongKhang** [comment]
Hi @LooperzZ, please check the details of the installation in [README.md](https://github.com/TruongKhang/TopicFM/blob/main/README.md)

**Comment by LooperzZ** [comment]
readme.md :This code implements [TopicFM+], which is an extension of [TopicFM]. For the implementation of previous version TopicFM, please checkout the aaai23_ver branch.

The main branch is TopicFM+? aaai23_ver Is it TopicFM? However, the weight file of the main branch loading TopicFM+ reports an error.

**Comment by TruongKhang** [comment]
I'll delete `pretrained/model_best.ckpt` in the main branch. This file corresponds to **TopicFM** in the `aaa23_ver` branch.

For **TopicFM_fast** and **TopicFM+**, I provided the download links in README.md. Did you have any problems when running with these two pre-trained models? Can you provide errors in detail?

**Comment by LooperzZ** [comment]
Traceback (most recent call last):
  File "C:\Users\86132\Desktop\TopicFM-main\demo\demo.py", line 86, in <module>
    matcher.load_state_dict(ckpt_dict['state_dict'])
  File "C:\Users\86132\Desktop\TopicFM-main\src\models\topic_fm.py", line 99, in load_state_dict
    return super().load_state_dict(state_dict, *args, **kwargs)
  File "D:\software\anaconda\envs\pytorch-gpu\lib\site-packages\torch\nn\modules\module.py", line 1483, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for TopicFM:
	Unexpected key(s) in state_dict: "coarse_net.feat_aug.2.q_proj.weight", "coarse_net.feat_aug.2.k_proj.weight", "coarse_net.feat_aug.2.v_proj.weight", "coarse_net.feat_aug.2.merge.weight", "coarse_net.feat_aug.2.mlp.0.weight", "coarse_net.feat_aug.2.mlp.2.weight", "coarse_net.feat_aug.2.norm1.weight", "coarse_net.feat_aug.2.norm1.bias", "coarse_net.feat_aug.2.norm2.weight", "coarse_net.feat_aug.2.norm2.bias", "coarse_net.feat_aug.3.q_proj.weight", "coarse_net.feat_aug.3.k_proj.weight", "coarse_net.feat_aug.3.v_proj.weight", "coarse_net.feat_aug.3.merge.weight", "coarse_net.feat_aug.3.mlp.0.weight", "coarse_net.feat_aug.3.mlp.2.weight", "coarse_net.feat_aug.3.norm1.weight", "coarse_net.feat_aug.3.norm1.bias", "coarse_net.feat_aug.3.norm2.weight", "coarse_net.feat_aug.3.norm2.bias". 

when i use the weight file-TopicFM_plus.pth.

**Comment by TruongKhang** [comment]
Hello @LooperzZ, which `config` file did you use for your code? For `TopicFM_plus.pth`, the settings of model should follow [this](https://github.com/TruongKhang/TopicFM/blob/main/configs/megadepth_test_topicfmplus.py)

**Comment by LooperzZ** [comment]
There is no question.thank you !
