### ISSUE TITLE
fine level correspondance

### ISSUE THREAD

**Issue by Moreland-cas** [TruongKhang/TopicFM#17]
Great work!
Could you explain a little bit why the self-supervised loss (symmetric epipolar distance) will encourage the model to find the most informative point in patch A?

**Comment by TruongKhang** [comment]
Thank you for your question @Moreland-cas,

We define the ground truth pairs of matches and then train the model. However, finding explicitly the most highly matchable point in a patch to extract ground truth is challenging. Instead, using a self-supervised loss to implicitly detect the highly matchable points is more reasonable. 
We used a detector network to estimate a score for each point in patch A. It is observed that the points in the flat regions (with similar intensity values) will yield the same score while the peak point will give the highest score. Therefore, the peak point will be chosen as the keypoint of interest.

**Comment by Moreland-cas** [comment]
> Thank you for your question @Moreland-cas,
> 
> We define the ground truth pairs of matches and then train the model. However, finding explicitly the most highly matchable point in a patch to extract ground truth is challenging. Instead, using a self-supervised loss to implicitly detect the highly matchable points is more reasonable. We used a detector network to estimate a score for each point in patch A. It is observed that the points in the flat regions (with similar intensity values) will yield the same score while the peak point will give the highest score. Therefore, the peak point will be chosen as the keypoint of interest.

Thanks, it make sense that points within flat regions will produce similar intensity values.
Also, have you investige how many pixels of error still exist in the fine level stage, is there any room of improvement?

**Comment by TruongKhang** [comment]
@Moreland-cas , we didn't. But as you might know, the fine-level correspondences are estimated at a half-resolution of input images. So if we can refine the matches at the full resolution of images, we can improve the performance. But this comes with higher computation costs

**Comment by Moreland-cas** [comment]
> @Moreland-cas , we didn't. But as you might know, the fine-level correspondences are estimated at a half-resolution of input images. So if we can refine the matches at the full resolution of images, we can improve the performance. But this comes with higher computation costs

I see, Thanks again for your work and quick reply :)

**Comment by Moreland-cas** [comment]
> @Moreland-cas , we didn't. But as you might know, the fine-level correspondences are estimated at a half-resolution of input images. So if we can refine the matches at the full resolution of images, we can improve the performance. But this comes with higher computation costs

I see, Thanks again for your work and quick reply :)
