### ISSUE TITLE
Data type error in DynamicFineMatching forward()

### ISSUE THREAD

**Issue by ceubel-pr** [TruongKhang/TopicFM#19]
Hello,

With the latest model weights ([topicfm_fast.ckpt](https://github.com/TruongKhang/TopicFM/blob/main/pretrained/topicfm_fast.ckpt)) and default config, I am getting an error at the very end of the DynamicFineMatching forward(...) function [here](https://github.com/TruongKhang/TopicFM/blob/3c17f3a3841b23bc38eb9e3d6ab24f1196f82dfa/src/models/utils/fine_matching.py#L158)

The exception reads:
```    
scale0_f, scale1_f = scale0[true_matches], scale1[true_matches]
TypeError: 'float' object is not subscriptable
```

I believe this is because `self.scale0` and `self.scale1` are not properly set as tensors and remain floats [here](https://github.com/TruongKhang/TopicFM/blob/3c17f3a3841b23bc38eb9e3d6ab24f1196f82dfa/src/models/utils/fine_matching.py#L105-L106). I've looked all around to see where these might be set but I cannot find them.
Honestly, I don't really understand how the code/architecture works, but I got an [older version of the codebase](https://github.com/Vincentqyw/TopicFM/tree/f875b5bf647c237aadd53ccebbee7e99b36920b8) working out of the box, using [image-matching-webgui](https://github.com/Vincentqyw/image-matching-webui/tree/main)

Could you explain what these scale attributes are and if there is a workaround for this issue?

Thank you! This is very impressive work and super helpful to my project

**Comment by TruongKhang** [comment]
Hi @ceubel-pr, thank you for reporting this minor issue. 

I guess if you add two tensors `scale0` and `scale1` into the input dict `data`, this issue can be resolved. The `scale` here is a ratio between original input image and the resized image. For example, if your image has a size of (960, 1200) and then you resize this image to (480, 600) to use in the model, the `scale` here should be [2, 2].

If you don't want to add the `scale` to the input data (we perform matching at the original size of images in this case), we can change the code as follows:

    scale0_f = scale0[true_matches] if isinstance(scale0, torch.Tensor) else scale0 # in this case, scale0 = 1 is a scalar value
    scale1_f = scale1[true_matches] if isinstance(scale1, torch.Tensor) else scale1 

I will fix this error soon! Thank you

**Comment by TruongKhang** [comment]
fixed!!!

**Comment by ceubel-pr** [comment]
Awesome! Thank you so much for your timely support on this!
