### ISSUE TITLE
when the code will be released?

### ISSUE THREAD

**Issue by Penge666** [TruongKhang/TopicFM#2]
Hello, author. I just read your paper and it's really good. I want to ask when the code will be released? I want to learn!!

**Comment by TruongKhang** [comment]
Hi @1280032578, 
We are in the progress to release at the end of this month (after receiving the final decision from the conference)
Please follow this repo to get a notification as earliest as possible!

**Comment by Penge666** [comment]
> Hi @1280032578, We are in the progress to release at the end of this month (after receiving the final decision from the conference) Please follow this repo to get a notification as earliest as possible!

OK, thank you~

**Comment by TruongKhang** [comment]
Hi @1280032578 , our code has been initially released!
