### ISSUE TITLE
Feature Extraction

### ISSUE THREAD

**Issue by jia199903** [TruongKhang/TopicFM#21]
Hello,author, I would like to inquire why feature extraction is often performed on single-channel gray images. What are the advantages of this approach and is it possible to use three-channel color images for feature extraction?

**Comment by TruongKhang** [comment]
Hi @jia199903, I think there is no special advantage when using gray images. If you train your model with your dataset, I recommend using RGB images instead. The main reason why some methods use gray images is because of evaluation on the HPatches dataset (this dataset only includes gray images).

**Comment by jia199903** [comment]
Sure, thank you very much for your response！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月6日(星期一) 晚上8:56
收件人: "TruongKhang/TopicFM";
抄送: "Mention";
主题: Re: [TruongKhang/TopicFM] Feature Extraction (Issue #21)





 
Hi @jia199903, I think there is no special advantage when using gray images. If you train your model with your dataset, I recommend using RGB images instead. The main reason why some methods use gray images is because of evaluation on the HPatches dataset (this dataset only includes gray images).
 
&mdash;

**Comment by jia199903** [comment]
Hello,author, @TruongKhang ，I want to know if this method can be used for image registration or image stitching tasks？I look forward to your reply.

**Comment by TruongKhang** [comment]
It depends on whether the two tasks require feature matching or not. I'm not an expert in those so I can't tell you in detail.

**Comment by jia199903** [comment]
@TruongKhang 
Thank you very much for your response！
![image](https://github.com/TruongKhang/TopicFM/assets/126779643/9daf586c-4790-46cc-95be-0fda4fe283d7)
if this features here are  already enhanced features by Topic-aware,Can I directly use the features obtained here to do correlation calculations？

**Comment by TruongKhang** [comment]
Hi @jia199903 , yes, the features `feat_c0` and `feat_c1` are enhanced using topics. But remember that these features are extracted at low-resolution images (`H/8 x W/8`)
