### ISSUE TITLE
mask

### ISSUE THREAD

**Issue by jia199903** [TruongKhang/TopicFM#22]
Hi,author
![image](https://github.com/TruongKhang/TopicFM/assets/126779643/14efb315-f769-4a8a-933f-429d083248e0)
![1715139043447](https://github.com/TruongKhang/TopicFM/assets/126779643/df01677f-7325-4a7b-8f36-7ac7e24fad54)
I'm a little confused about the mask here，I understand this mask to refer to the useful area after padding(padding (bool): If set to 'True', zero-pad resized images to squared size.),I want to know if the image’s size of my dataset is  squared size,Can I skip these steps(resize,padding...) and set the mask to none.
Expect your reply.

**Comment by TruongKhang** [comment]
@jia199903 , yes, of course you can skip masking, resizing, or padding when testing with your data.
The reason for using a mask here is because of training with the Megadepth dataset (input images do not have the same size).
But when you run testing or evaluation, the masks can be ignored!

**Comment by jia199903** [comment]
Thank you.
