### ISSUE TITLE
How to run the demo with a pair of images?

### ISSUE THREAD

**Issue by cxmscb** [TruongKhang/TopicFM#6]
Hello
I have no idea about how to run the TopicFM demo with a pair of images. 
Any help would be appreciated.

**Comment by TruongKhang** [comment]
Hi @cxmscb, to run a demo with an image pair, you just need to put your pair in a folder and then run this command:

    python visualization.py --run_demo --method topicfm --dataset_dir <path/to/your/demo_folder> --dataset_name aachen_v1.1

We also provide several options for running demo:
- when your folder has multiple images, the program will pick the first image as a reference image. Then, it iterates through the other images to perform matching with the reference one.
- You can also provide a `.txt` file which contains a list of images. Then, the program can run demo only for this list of images as follows

      python visualization.py --run_demo --method topicfm --dataset_dir <path/to/your/image_folder>  --dataset_name aachen_v1.1 --pair_dir <path/to/your/txt_file>

Hope this help. Please let me know if there is any problems.
