### ISSUE TITLE
Contact Author

### ISSUE THREAD

**Issue by Penge666** [TruongKhang/TopicFM#7]
Hello, the author. After reading your article, I learned a lot. I am a graduate student in school, and I am also studying image feature matching. I want to ask if the author can leave an email or other ways to learn from you. If you can, thank you very much!

**Comment by TruongKhang** [comment]
Hello Mr. Kevin, please check out the latest version of our paper [here](https://arxiv.org/pdf/2207.00328.pdf). We share all contact information there! 
I am also a graduate student. If you have any questions, you can discuss with me in this Github as well. I'm always active :D

**Comment by Penge666** [comment]
> Hello Mr. Kevin, please check out the latest version of our paper [here](https://arxiv.org/pdf/2207.00328.pdf). We share all contact information there! I am also a graduate student. If you have any questions, you can discuss with me in this Github as well. I'm always active :D

That's fine. Thank you very much!
